######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 18 10:32:06 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circleWidget.h imageWidget.h window.h
SOURCES += circleWidget.cpp imageWidget.cpp main.cpp window.cpp
