######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 3 15:27:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circleFinder.h circleWidget.h imageWidget.h tableWidget.h window.h
SOURCES += circleWidget.cpp imageWidget.cpp main.cpp tableWidget.cpp window.cpp
